### ISSUE TITLE
SEVERE BUG: in opening link card in canvas and data lose

### ISSUE THREAD

**Issue by Coolguyzv** [nekoshita/obsidian-auto-card-link#71]
when you open a link card in obsidian canvas it sometimes opens directly in your browser which's the default behavior and sometimes it opens in the page itself with embedded view which's break the current page and delete everything on it from any content

**Comment by albertoloscerritos** [comment]
I have gotten the exact same behavior with this plugin and with the following plugin: https://github.com/Meikul/obsidian-thumbnails
I don't know exactly how to replicate it, but after clicking in the card link (or youtube thumbnail) for a couple of times (sometimes after just the second time clicking it) instead of launching the webpage in the default explorer it opens it as an embebed webpage inside the card. As you mentioned, it only happens sometimes.
I got the same behavior as you mentioned:
- It only happens in canvas cards
- Obsidian becomes very laggy
- The only way to fix it is to delete the card, or the content will be deleted after a couple of clicks

This is how it originally looks:
![image](https://github.com/user-attachments/assets/1931a428-1795-466c-bc2d-a8e12a453834)

This is how it looks after the bug happpens:
![image](https://github.com/user-attachments/assets/5dec08c0-82b6-4d9e-9347-b3503a06aede)

This is how it looks after the content is deleted (automatically after clicking around):
![embed link](https://github.com/user-attachments/assets/aa61d18d-2e64-4ffc-8997-0e47e4b6bb82)
As you can see from the previous gif, the card in question gets it content removed and is render 
"useless" I can't type in it, and the editing toolbar also gets stuck:
![embed link 2](https://github.com/user-attachments/assets/019f85db-5fa8-4573-a4ed-f0af57b80ac0)

I get the following 3 errors in the console log after the error happens:

```
app.js:1 Uncaught DOMException: Blocked a frame with origin "app://obsidian.md" from accessing a cross-origin frame.
    at e.removeWindowListeners (app://obsidian.md/app.js:1:438569)
    at e.destroy (app://obsidian.md/app.js:1:439113)
    at e.destroy (app://obsidian.md/app.js:1:454948)
    at t.destroy (app://obsidian.md/app.js:1:1623364)
    at t.destroyEditor (app://obsidian.md/app.js:1:1664479)
    at t.showPreview (app://obsidian.md/app.js:1:1664855)
    at t.blur (app://obsidian.md/app.js:1:2669273)
    at app://obsidian.md/app.js:1:2622197
e.removeWindowListeners @ app.js:1
e.destroy @ app.js:1
e.destroy @ app.js:1
t.destroy @ app.js:1
t.destroyEditor @ app.js:1
t.showPreview @ app.js:1
t.blur @ app.js:1
(anonymous) @ app.js:1
requestAnimationFrame (async)
e.requestFrame @ app.js:1
e.updateSelection @ app.js:1
e.deselectAll @ app.js:1
e.onPointerdown @ app.js:1
app.js:1 Uncaught DOMException: Blocked a frame with origin "app://obsidian.md" from accessing a cross-origin frame.
    at e.removeWindowListeners (app://obsidian.md/app.js:1:438569)
    at e.destroy (app://obsidian.md/app.js:1:439113)
    at e.destroy (app://obsidian.md/app.js:1:454948)
    at t.destroy (app://obsidian.md/app.js:1:1623364)
    at t.destroyEditor (app://obsidian.md/app.js:1:1664479)
    at t.showPreview (app://obsidian.md/app.js:1:1664855)
    at t.blur (app://obsidian.md/app.js:1:2669273)
    at app://obsidian.md/app.js:1:2622197
e.removeWindowListeners @ app.js:1
e.destroy @ app.js:1
e.destroy @ app.js:1
t.destroy @ app.js:1
t.destroyEditor @ app.js:1
t.showPreview @ app.js:1
t.blur @ app.js:1
(anonymous) @ app.js:1
requestAnimationFrame (async)
e.requestFrame @ app.js:1
e.onResize @ app.js:1
(anonymous) @ app.js:1
r @ enhance.js:1
DevTools failed to load source map: Could not load content for https://static-assets-eu.libguides.com/web/css3.12.4/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'head')
    at t.onIframeLoad (app.js:1:1660923)

```

![image](https://github.com/user-attachments/assets/16d5f977-1a32-4317-a4f0-995e613a6202)



I am lead to believe that this is an issue with obsidian, and how canvas/cards handle the process of launching externals links
Hopefully we can find a fix for this issue

I am using obsidian 1.7.4 and windows 11

**Comment by albertoloscerritos** [comment]
@nekoshita please let us know if you think this is a bug caused by the plugin, or by obsidian, in which case we can report it in the obsidian forum. Thanks.
